export const ADVANTAGES_LIST =
[
  'Komunikatywność',
  'Zespołowość',
  'Przedsiębiorczość',
  'Zaangażowanie',
  'Lojalność',
  'Analityczne myślenie',
  'Logiczne myślenie',
  'Kreatywność',
  'Elastyczność',
  'Zarządzanie zespołem',
  'Negocjacje',
  'Krytyczne myślenie',
  'Asertywność',
  'Zorientowanie na cel',
  'Odporność na stres',
  'Otwartość',
  'Inteligencja emocjonalna',
  'Terminowość',
  'Sumienność',
  'Odpowiedzialność',
  'Życzliwość',
  'Podejmowanie decyzji',
  'Nawiązywanie relacji'
]